#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

set +e

echo "Running ESLint..."
npm run lint
LINT_STATUS=$?

# Check if trufflehog is installed
if ! command -v trufflehog >/dev/null 2>&1; then
  echo  trufflehog not found"
  echo " Install it using: apt install trufflehog"
  GG_STATUS=1
else
  echo "🔐 Running trufflehog secret scan..."
trufflehog git file://. --since-commit HEAD --only-verified --fail
  GG_STATUS=$?
fi

echo "----------------------------"

if [ $LINT_STATUS -ne 0 ]; then
  echo "❌ ESLint failed"
else
  echo "✅ ESLint passed"
fi

if [ $GG_STATUS -ne 0 ]; then
  echo "❌ trufflehog secret scan failed"
else
  echo "✅ trufflehog secret scan passed"
fi

echo "----------------------------"

# Fail commit if any check failed
if [ $LINT_STATUS -ne 0 ] || [ $GG_STATUS -ne 0 ]; then
  echo "🚫 Pre-commit checks failed. Commit aborted."
  exit 1
fi

echo "🎉 All pre-commit checks passed!"
exit 0
