#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

set +e

echo "Running ESLint..."
npm run lint
LINT_STATUS=$?

# Check if gitleaks is installed
if ! command -v gitleaks >/dev/null 2>&1; then
  echo  "gitleaks not found"
  echo " Install it using: apt install gitleaks"
  GG_STATUS=1
else
  echo "🔐 Running gitleaks secret scan..."
  gitleaks protect --staged  -v
  GG_STATUS=$?
fi

echo "----------------------------"

if [ $LINT_STATUS -ne 0 ]; then
  echo "❌ ESLint failed"
else
  echo "✅ ESLint passed"
fi

if [ $GG_STATUS -ne 0 ]; then
  echo "❌ gitleaks secret scan failed"
else
  echo "✅ gitleaks secret scan passed"
fi

echo "----------------------------"

# Fail commit if any check failed
if [ $LINT_STATUS -ne 0 ] || [ $GG_STATUS -ne 0 ]; then
  echo "🚫 Pre-commit checks failed. Commit aborted."
  exit 1
fi

echo "🎉 All pre-commit checks passed!"
exit 0
